version: "3"
services:
  mongodb:
    container_name: notion-investment-integration-database
    image: mongo:4.4
    ports:
      - 27018:27017
    restart: "no"
    volumes:
      - ./infra/mongo:/data/db
