permissions:
  contents: write

name: Architecture Consistency Check

on:
  push:
    branches:
      - feat/add-new-project

jobs:
  run_architecture_checker_ai_agent:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - project_name: "kindlefy"
            folder_path: "examples/kindlefy"
            llm_provider: "gemini"
            target_files: "*.ts"
          - project_name: "js"
            folder_path: "examples/js"
            llm_provider: "openai"
            target_files: "*.js"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install openai
          pip install google-generativeai

      - name: Run AI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          all_files=$(find ${{ matrix.target.folder_path }} -type f -name '${{ matrix.target.target_files }}')
          python3 ai-agents/architecture-checker/run.py --provider ${{ matrix.target.llm_provider }} $all_files
